spring:
  application:
    name: ABT-bio

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50

  jpa:
    hibernate:
      ddl-auto: update             # validate
      default_schema: public
      default_batch_fetch_size: 50
    show-sql: false

  #  flyway:
  #    enabled: true
  #    baseline-on-migrate: true
  #    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

app:
  jwt:
    valid-duration: 3600
    refreshable-duration: 3600

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
